/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dwdyggbowymswxuunkgl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZHlnZ2Jvd3ltc3d4dXVua2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE0MzMzMDAsImV4cCI6MjA5NzAwOTMwMH0.3yMwnxuZml-k32OZpmbM-7vbYJdUr4czNJi74x9YsxU"